web:
    image: nginx:stable
    volumes:
        - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./web:/var/www/public:ro
    links:
        - node
    ports:
        - "80:80"

node:
    image: node:7
    command: node /usr/src/app/app.js
    volumes:
        - ./node:/usr/src/app
    links:
        - mongo
    ports:
        - "3000:3000"

mongo:
    image: mongo:3
    volumes:
        - ./db:/data/db
